### ISSUE TITLE
Bootloader stop working after upload TestAndMeasurement.bin (with a workaround)

### ISSUE THREAD

**Issue by DaviVolcan** [xyphro/UsbGpib#3] opened 2020-03-05 22:35 UTC
i followed the flassing instructions as in readme...
im using an arduino as isp and avrdudess (GUI for avrdude) to upload the bootloader... then i disconect the programmer and conect via usb the board... the mass storage shows up as spected but after delete flash.bin and replacing bt TestAndMeasurement.bin then porwercicled the board... i cant get bootloader to work when jumping the correct isp pins... 
i tried several boards whit no luck... But for some reason to test the boards i decide to burn the arduino leonardo bootloader in one of the boards... i got is to work... then i tried again the flahsing procedure for this project... Now everthing works! i think that arduino ide programmed the fuses. now i can reboot a billion times whitout any issues...

**Comment by Wilts01** [comment] 2020-04-19 19:52
Hi, I have the same problem.  I used a USBASP as a programmer with avrdude command line.  I uploaded the boot loader and connected via USB.  I showed up as a new drive and I copied across TestAndMeasurement.bin to replace flash.bin.  However, when I connect it up to a GPIB port, it doesn't show up in either Device Manager or VISA.  The led is just very faintly on and if I short the ISP pins, it doesn't show up as a USB drive.  What am I missing here?  Should I try burning the arduino leonardo bootloader?  If so, how do I do that?

Thanks  Paul

**Comment by Xyp** [comment] 2020-04-19 20:04
Hi Paul, can you share the fuse settings? Is it possible, that the jtag interface is not disabled in the fuse settings?
Best regards, 
Kai

**Comment by Wilts01** [comment] 2020-04-19 20:04
Ah found out.  I was able to use the Arduino IDE to programme the Arduino Bootloader for a Leonardo board using my USBASP.  Even though it claimed to have failed, it did enough to allow me to reinstall the proper bootloader and get it working.

**Comment by Wilts01** [comment] 2020-04-19 20:05
Kai, How do I do that?  Sorry, not done a lot of AVR work before
Paul
PS - I did manage to get it working with Davi's workaround

**Comment by Wilts01** [comment] 2020-04-19 20:07
I installed the original bootloader with the command line avrdude -c usbasp -p m32u4 -U flash:w:Bootloader.hex  so didn't do anything special with fuses

**Comment by xyphro** [comment] 2020-04-19 20:12
Hi Wilts01,

if you have it working, very good. 

Actually this whole thing was never done using any Arduino stuff (I am one of those, that programmed the first AVRs, when there was not even a C compiler available). 
I suspect, that the reason, why using the Arduino bootloader is, that the Arduino bootloader programming sets Fuses correctly. Those fuses select, if the Jtag interface is on or off (it should be off), the clock source (shoud be High frequency XTAL), boot sector size, ...
Typically this is done using additional parameters to avrdude.

Best regards,

Kai

**Comment by Wilts01** [comment] 2020-04-19 21:15
Thanks Kai.  Do you have a definitive list of what the fuses should be?  BTW, I have created a BOM in Excel if you would fine that useful.

Cheers

Paul

**Comment by Xyp** [comment] 2020-04-20 06:52
Hi Paul,

I will take this up in the readme im the scope of this week. Providing a clear description of how to do the 1st program with correct commandline parameters to avrdude is something required here to help others to create their own copies of this and avoid buiding up frustration. 

Best regards, 

Kai

**Comment by Xyp** [comment] 2020-04-20 07:19
Sorry, forgot 1 thing: an excel bom is valued. Can you add it yourself? To the repository? Otherwise you can mail it to xyphro at gmail.com and I will add.

**Comment by motechsolutions** [comment] 2020-04-21 20:50
Just finishing building my first UsbGpib and i found the same problem when using a USBasp programmer.
After reading the above comments i looked at the fuses the Arduino IDE used to write the arduino leonardo bootloader and added these to my bat file and now my UsbGpib working :)

I also found i needed to install the Keysight IO Libraries Suite for Windows 10 to recognize the UsbGpib

If it helps anyone my .bat file is

@echo off
title code_burnATMEGA32U4
echo !!Welcome to usbasp programmer!!
echo !!Programing Fuses!!
avrdude -c usbasp -p m32u4 -e -Ulock:w:0x3F:m -Uefuse:w:0xcb:m -Uhfuse:w:0xd8:m -Ulfuse:w:0xff:m
pause
echo !!Writing BootLoader!!
avrdude -c usbasp -p m32u4 -U flash:w:BootLoader.hex
pause

**Comment by motechsolutions** [comment] 2020-04-21 22:13
Can anyone recommend any software i can use to get voltage reading data from a HP 3457a.
My plan was to read the data using pyvisa then post the readings to Grafana via MQTT
Problem is im a newbie at both GPIB and pivisa, any help would be much appreciated.
The hardware route i was thinking of was UsbGpib to Raspi zero then post via wifi to MQTT server and on to Grafana

**Comment by xyphro** [comment] 2020-04-22 06:01
Hi!

Thanks for sharing the fuses. Was just struggling yesterday night to get my AvrDargon up and running, so thanks for your help!

You have luck: I own the HP3457a too :-)
There was a major hurdle to get it up and running, because the EOI termination is default wise not on after power on, which is mainly because it is an older test equipment. 
However: Once I found the cause, I got the solution. Sending the command "END ALWAYS" enables it.
Get an operation manual for the HP3457a from the web to see more commands. Note: The HP3455a has a completely different comand set, so really ensure you get the manual for the HP3457a.

Below a freshly tested python (3.x) snippet to read out the voltage:
-----------8<-----------8<-----------8<-----------8<-----------8<-----------8<-----------
import pyvisa as visa

rm = visa.ResourceManager()
VM = rm.open_resource('USB0::0x03EB::0x2065::GPIB_22_7583932313435131D140::INSTR') #Note: Put here your VISA ressource string for the multimeter, above is mine, your's might be different

VM.write('END ALWAYS') # Turn on EOI generation (VERY IMPORTANT!)
VM.write('DCV') # Switch to DC volt mode with AUTO range
voltage = float(VM.read().strip()) # Read voltage as ASCII string and convert to float
print(voltage)

**Comment by motechsolutions** [comment] 2020-04-22 11:08
Hi xyphro
Thank you for this info, its just saved me hours of hunting google.
Ill give these commands a go and let you know how i get on.
Have you tried your UsbGpib interface with IanJ python script for the HP 3457A, looks really good if i can get it working :)
https://www.eevblog.com/forum/metrology/3458a-logging-via-windows-app-revisited/

**Comment by motechsolutions** [comment] 2020-04-23 16:03
Hi xyphro
Quick question: What command do you use to set the NPLC to 100, ive tried 
VM.write('NPLC 100') but i get a timeout error but if i use VM.write('NPLC 10') which i believe sets the Power line cycles to 10 or do i need to increase the command timeout in pivisa, if so how to i do that?
so far my script looks like

```
import pyvisa as visa
import paho.mqtt.client as mqttClient
import time

rm = visa.ResourceManager()
VM = rm.open_resource('USB0::0x03EB::0x2065::GPIB_22_75935313330351D01201::0::INSTR') #VISA ressource string for the multimeter.
VM.write('END ALWAYS') # Turn on EOI generation)
VM.write('DCV') # Switch to DC volt mode with AUTO range
VM.write('NPLC 100') #Set power line cycles to 100
VM.write('NRDGS 1') #Set number of readings per trigger

def on_connect(client, userdata, flags, rc):
    if rc == 0:
        #print("Connected to broker")
        global Connected                #Use global variable
        Connected = True                #Signal connection
    else:
        print("Connection failed")
Connected = False   #global variable for the state of the connection

broker_address= "********"
port = 1883
user = "********"
password = "********"

client = mqttClient.Client("hp3457a")               #create new instance
client.username_pw_set(user, password=password)    #set username and password
client.on_connect= on_connect                      #attach function to callback
client.connect(broker_address, port=port)          #connect to broker

client.loop_start()        #start the loop

while Connected != True:    #Wait for connection
    time.sleep(0.1)

try:
    while True:
        voltage = float(VM.read().strip()) # Read voltage as ASCII string and convert to float
        client.connect(broker_address, port=port) #connect to broker
        client.publish("/sensors/HP3457A/dcV",voltage) #Publish to MQTT Broker
        #print(voltage)
        time.sleep(5)

except KeyboardInterrupt:
```

**Comment by Xyp** [comment] 2020-04-23 16:18
Hi!
Can you mail be, as this is off topic to the original issue? Xyphro at gmail.com
Will check it out. 
Best regards, 

Kai

**Comment by motechsolutions** [comment] 2020-04-23 16:55
Will do :)

**Comment by xyphro** [comment] 2020-04-23 20:42
I have updated just updated the instructions using the input from motechsolutions. 
Thanks! Closing the ticket now.

**Closed by xyphro** 2020-04-23 20:42 UTC
